<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-G8DF7AO" failures="6" tests="13" name="Calculator Test" time="0.079" errors="0" timestamp="2023-01-22T21:12:37 EET">
  <testcase classname="org.internship.CalculatorTest" name="testCalculator" time="0.005"/>
  <testcase classname="org.internship.CalculatorTest" name="testCalculator" time="0.0"/>
  <testcase classname="org.internship.CalculatorTest" name="testCalculator" time="0.001"/>
  <testcase classname="org.internship.CalculatorTest" name="testCalculator" time="0.0"/>
  <testcase classname="org.internship.CalculatorTest" name="testCalculator" time="0.0"/>
  <testcase classname="org.internship.CalculatorTest" name="testCalculator" time="0.001"/>
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorSoftAssert" time="0.01">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Intentionally failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Intentionally failed! expected [true] but found [false]
at org.internship.CalculatorTest.testCalculatorSoftAssert(CalculatorTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testCalculatorSoftAssert -->
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorSoftAssert" time="0.0">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Intentionally failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Intentionally failed! expected [true] but found [false]
at org.internship.CalculatorTest.testCalculatorSoftAssert(CalculatorTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testCalculatorSoftAssert -->
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorSoftAssert" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Intentionally failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Intentionally failed! expected [true] but found [false]
at org.internship.CalculatorTest.testCalculatorSoftAssert(CalculatorTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testCalculatorSoftAssert -->
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorSoftAssert" time="0.0">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Intentionally failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Intentionally failed! expected [true] but found [false]
at org.internship.CalculatorTest.testCalculatorSoftAssert(CalculatorTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testCalculatorSoftAssert -->
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorSoftAssert" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Intentionally failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Intentionally failed! expected [true] but found [false]
at org.internship.CalculatorTest.testCalculatorSoftAssert(CalculatorTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testCalculatorSoftAssert -->
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorSoftAssert" time="0.001">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Intentionally failed! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Intentionally failed! expected [true] but found [false]
at org.internship.CalculatorTest.testCalculatorSoftAssert(CalculatorTest.java:48)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- testCalculatorSoftAssert -->
  <testcase classname="org.internship.CalculatorTest" name="testCalculatorWithPrivate" time="0.0"/>
  <testcase classname="org.internship.CalculatorTest" name="testEnableFalse" time="0.0">
    <ignored/>
  </testcase> <!-- testEnableFalse -->
</testsuite> <!-- Calculator Test -->
